### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by joy002** [EShults2124/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
   - use backticks for the code example. For instance, `scp`, `ls`, etc.
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - Didn't count keystrokes. From Lab1: Write down in notes First try using just what we learned in this lab, and document the best process you came up with. Try to get the total time for a run after editing and saving to under 10 total keystrokes/mouse clicks, including all typing.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good job:)

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by joy002** [comment]
Hi, I reviewed your lab report. One more thing you still need to fix: use backticks(`) for all relevant code.

**Comment by EShults2124** [comment]
I hope that I finally did it right. I completely misunderstood what "relevant code" meant so that's why it took so long to get it the way is not. Thank you very much for your patience! This has really been stressing me out.

**Comment by joy002** [comment]
I have updated your grade, leave me a comment if there is any other questions.

**Comment by EShults2124** [comment]
Thank you so much
